services:
  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:18
    container_name: usigrabber_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-usigrabber}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - usigrabber_helix_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "wal_compression=on"
      - "-c"
      - "max_wal_size=16GB"
      - "-c"
      - "shared_buffers=18GB"
      - "-c"
      - "work_mem=128MB"
      - "-c"
      - "maintenance_work_mem=2GB"

volumes:
  usigrabber_helix_pgdata:
  loki-data:
  grafana-data:
