line-length = 100

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # https://docs.astral.sh/ruff/rules/missing-newline-at-end-of-file/
    "W292"
]
# Got annoyed with line length
ignore = ["E501"]


[format]
# Use tabs instead of 4 space indentation.
indent-style = "space"
