apiVersion: 1

datasources:
  - name: usigrabber-postgres
    uid: usigrabber-postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: host.docker.internal:5433
    database: ${POSTGRES_DB:-usigrabber}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: true
    editable: true

  - name: usigrabber-loki
    uid: usigrabber-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
