{
 "title": "DB Info",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "PSM Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT row_count FROM psm_growth_stats ORDER BY measured_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "PSMs per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($latest-$previous)/$timedelta", "reducer": "last", "type": "math" }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "description": "Empty projects have 0 mzID files (and therefor 0 PSMs) associated with them",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as all_count FROM projects;"
    },
    {
     "rawSql": "SELECT COUNT(*) as empty_count FROM (SELECT p.accession, COUNT(mf.*)\r\nFROM projects p\r\nLEFT JOIN mzid_files mf ON mf.project_accession = p.accession\r\nGROUP BY p.accession\r\nHAVING COUNT(mf.*) = 0);"
    },
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "PSM count over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  measured_at AS \"time\",\r\n  row_count AS \"Total\",\r\n  GREATEST(0, row_count - LAG(row_count) OVER (ORDER BY measured_at)) AS \"Change\"\r\nFROM psm_growth_stats\r\nWHERE $__timeFilter(measured_at)\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Projects by submission type",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT submission_type, COUNT(*) FROM projects GROUP BY submission_type;"
    }
   ]
  },
  {
   "title": "CV Params",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(count) as \"Average per project\", SUM(count) as \"Total\" FROM (SELECT COUNT(*)  FROM project_cv_params GROUP BY project_accession)"
    }
   ]
  }
 ]
}