{
 "title": "Error Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project_accession" },
   { "name": "job_id" }
  ]
 },
 "panels": [
  {
   "title": "Processed Files",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT is_processed_successfully, COUNT(*) FROM imported_files\ngroup by is_processed_successfully"
    }
   ]
  },
  {
   "title": "Projects with Failed Files",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT job_id, project_accession, COUNT(*) from imported_files where is_processed_successfully = false GROUP BY project_accession, job_id order by count DESC"
    }
   ]
  },
  {
   "title": "Project Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"usigrabber-test\", job_id=\"$job_id\"} | logfmt | project_accession = `$project_accession`",
     "maxLines": 1000
    }
   ]
  }
 ]
}